# NumPy Basics and Usage
NumPy is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions. This notebook will guide you through the basics of NumPy and show you how to use it effectively.

## Installing NumPy
To install NumPy, use the following command:
```
pip install numpy
```
You can also install it via conda if you're using Anaconda.

##### NOTE:

- When using Anaconda any time you want to install a package you will need to put the "!" infront of the pip
&nbsp;

    - This will work
      ```
          !pip install numpy
                 or
          !pip3 install numpy
      ```
      &nbsp;
    - This will not work
      ```
          pip install numpy
                 or
          pip3 install numpy
      ```

In [ ]:
!pip install numpy

## Creating Arrays
NumPy arrays are the core of the library. You can create arrays in several ways, using functions like `np.array`, `np.zeros`, `np.ones`, `np.empty`, `np.arange`, and `np.linspace`.

In [11]:
import numpy as np

# Creating an array from a list
array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)

# Creating an array of zeros
# The argument (3, 3) specifies the shape of the array. Here, it creates a 3x3 array filled with zeros.
zeros_array = np.zeros((3, 3))
print("\nArray of zeros:\n", zeros_array)

# Creating an array of ones
ones_array = np.ones((2, 4))
print("\nArray of ones:\n", ones_array)

# Creating an empty array
empty_array = np.empty((2, 2))
print("\nEmpty array:\n", empty_array)

# Creating an array with a range of values
# The arguments (0, 10, 2) specify the start (0), stop (10), and step size (2). Here, it creates an array with values [0, 2, 4, 6, 8].
range_array = np.arange(0, 10, 2)
print("\nArray with range:", range_array)

# Creating an array with evenly spaced values
# The arguments (0, 10, 5) specify the start (0), stop (10), and number of values (5). Here, it creates an array with 5 values evenly spaced between 0 and 10.
linspace_array = np.linspace(0, 10, 5)
print("\nLinspace array:", linspace_array)

Array from list: [1 2 3 4 5]

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Empty array:
 [[ 2.5  5. ]
 [ 7.5 10. ]]

Array with range: [0 2 4 6 8]

Linspace array: [ 0.   2.5  5.   7.5 10. ]


## Basic Array Operations
NumPy arrays support a variety of operations, such as addition, subtraction, multiplication, and division.

In [14]:
# Element-wise addition
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sum_array = array1 + array2
print("Sum of arrays:", sum_array)

# Element-wise multiplication
product_array = array1 * array2
print("\nProduct of arrays:", product_array)

# Dot product
dot_product = np.dot(array1, array2)
print("\nDot product of arrays:", dot_product)

Sum of arrays: [5 7 9]

Product of arrays: [ 4 10 18]

Dot product of arrays: 32


## Indexing and Slicing
NumPy arrays support advanced indexing and slicing to access and modify data.

In [17]:
array = np.array([10, 20, 30, 40, 50])

# Indexing
print("First element:", array[0])
print("\nLast element:", array[-1])

# Slicining
print("\nFirst three elements:", array[:3])
print("\nEvery other element:", array[::2])

# Multi-dimensional array slicing
multi_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nSub-array:\n", multi_array[0:2, 1:3])

First element: 10

Last element: 50

First three elements: [10 20 30]

Every other element: [10 30 50]

Sub-array:
 [[2 3]
 [5 6]]


## Array Manipulation

NumPy provides functions to reshape, flatten, and concatenate arrays


In [18]:
# Reshaping an array
reshaped_array = np.arange(6).reshape((2, 3))
print("Reshaped array:\n", reshaped_array)

# Flattening an array
flattened_array = reshaped_array.flatten()
print("\nFlattened array:", flattened_array)

# Concatenating arrays
concatenated_array = np.concatenate((array1, array2))
print("\nConcatenated array:", concatenated_array)


Reshaped array:
 [[0 1 2]
 [3 4 5]]

Flattened array: [0 1 2 3 4 5]

Concatenated array: [1 2 3 4 5 6]


## Mathematical Functions

NumPy includes a variety of mathematical functions, such as `np.sum`, `np.mean`, `np.sqrt`, and more


In [21]:
# Sum of elements
print("Sum of elements:", np.sum(array))

# Mean of elements
print("\nMean of elements:", np.mean(array))

# Square root of each element
print("\nSquare root of elements:", np.sqrt(array))

Sum of elements: 150

Mean of elements: 30.0

Square root of elements: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


## Broadcasting

Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes


In [22]:
# Broadcasting example
array3 = np.array([1, 2, 3])
array4 = np.array([[4], [5], [6]])
broadcasted_sum = array3 + array4
print("Broadcasted sum:\n", broadcasted_sum)

Broadcasted sum:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


## Matrix Multiplication

Matrix multiplication is a binary operation that produces a matrix from two matrices. NumPy provides the `np.dot()` function for this purpose.

In [24]:
# Multiplying two 2-dimensional arrays (matrices)
# Here we define a 2x3 matrix and a 3x2 matrix
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

# Performing matrix multiplication
result = np.dot(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nResult of matrix multiplication:\n", result)

Matrix 1:
 [[1 2 3]
 [4 5 6]]

Matrix 2:
 [[ 7  8]
 [ 9 10]
 [11 12]]

Result of matrix multiplication:
 [[ 58  64]
 [139 154]]


## Conclusion

This notebook has covered the basics of NumPy, including array creation, operations, and more. With these tools, you can start using NumPy for numerical computing tasks in Python.

## Extra Resources

Hyperlinks are attached to each of the extra resources

- [NumPy Tutorial](https://youtu.be/GB9ByFAIAH4?si=F63UUEK9E9u7IWVR)
    - Complete Python NumPy Tutorial (Creating Arrays, Indexing, Math, Statistics, Reshaping)
    - YouTube video
        - Time = 58 Minutes 
      
&nbsp;

- [NumPy Tutorial](https://realpython.com/numpy-tutorial/)
    - Complete beginner course for NumPy
          
&nbsp; 
     
- [Learn Data Sci](https://www.learndatasci.com/tutorials/applied-introduction-to-numpy-python-tutorial/)
    - NumPy Tutorial: An Applied Introduction for Beginners